[package]
name = "den-stdlib-console"
description = "Console API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
test = false


[dependencies]
rquickjs = { workspace = true, features = ["macro"] }
tracing.workspace = true

[dev-dependencies]
color-eyre.workspace = true
den-core = { workspace = true, features = ["stdlib"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
