[package]
name = "den-stdlib-crypto"
description = "Web Crypto API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
indexmap.workspace = true
rquickjs = { workspace = true, features = ["macro", "futures"] }
rand = "0.10.2"
sha1 = "0.10"
sha2 = "0.10"
uuid = { version = "1.24.1", features = ["fast-rng", "v4"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
