[package]
name = "den-stdlib-crypto"
description = "Web Crypto API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
den-util.workspace = true
indexmap.workspace = true
rquickjs = { workspace = true, features = ["macro", "futures"] }
rand.workspace = true
sha1.workspace = true
sha2.workspace = true
uuid = { workspace = true, features = ["fast-rng", "v4"] }

[dev-dependencies]
color-eyre.workspace = true
den-core = { workspace = true, features = ["stdlib"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
