[package]
name = "den-stdlib-crypto"
description = "Web Crypto API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
den-utils = { version = "*", path = "../den-utils", features = ["serde_json"] }
derivative.workspace = true
derive_more.workspace = true
either.workspace = true
getset = "0.1.7"
indexmap.workspace = true
rquickjs = { workspace = true, features = ["macro", "futures"] }
tracing.workspace = true
typed-builder.workspace = true
tokio = { workspace = true, features = ["sync"] }
rand = "0.10.2"
uuid = { version = "1.24.1", features = ["fast-rng", "v4"] }

[lints]
workspace = true
