[package]
name = "den-utils"
description = "Utilities for den"
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more.workspace = true
pin-project-lite = "0.2.14"
rquickjs.workspace = true
swc_core = { workspace = true, optional = true }
tokio = { workspace = true, features = [] }
tokio-util.workspace = true
trie-match = { version = "0.2.0", optional = true }

[features]
transpile = ["swc_core", "trie-match"]
typescript = ["transpile", "swc_core?/ecma_parser_typescript"]
react = ["transpile"]
