[workspace]

members = [
    "den-stdlib-console",
    "den-stdlib-core",
    "den-stdlib-networking",
    "den-stdlib-regex",
    "den-stdlib-timer",
    "den-utils"
]

[workspace.package]
version = "0.0.2"
edition = "2021"

[workspace.dependencies]
delegate = "0.10.0"
delegate-attr = "0.2.9"
derivative = "2.2.0"
derive_more = "0.99.17"
futures = "0.3.28"
rquickjs = { git = "https://github.com/stevefan1999-personal/rquickjs", branch = "patch-qjs-patch-without-gnu", version = "0.4.0-beta.4", features = ["full-async", "rust-alloc", "parallel", "max-args-7"] }
tokio = "1.32.0"
tokio-util = "0.7.8"

[package]
name = "den"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1.5.0"
clap = { version = "4.4.3", features = ["unicode", "derive", "env"] }
color-eyre = "0.6.2"
delegate-attr.workspace = true
den-stdlib-console = { version = "^0.0", path = "den-stdlib-console" }
den-stdlib-core = { version = "^0.0", path = "den-stdlib-core" }
den-stdlib-networking = { version = "^0.0", path = "den-stdlib-networking" }
den-stdlib-timer = { version = "^0.0", path = "den-stdlib-timer" }
den-utils = { version = "^0.0", path = "den-utils" }
derivative.workspace = true
derive_more.workspace = true
fmmap = { version = "0.3.2", features = ["tokio-async"] }
matchit = "0.7.2"
mime = "0.3.17"
phf = "0.10.1"
relative-path = "1.9.0"
reqwest = { version = "0.11.20", features = ["stream", "socks", "multipart", "json", "deflate", "gzip", "cookies", "blocking", "brotli", "native-tls"] }
rquickjs = { workspace = true, features = ["array-buffer", "allocator", "futures", "rust-alloc", "loader", "parallel", "phf"] }
rustyline = { version = "11.0.0", features = ["derive"] }
swc_core = { version = "0.74.6", features = ["ecma_codegen", "base_concurrent", "common_concurrent", "ecma_plugin_transform", "ecma_parser"], optional = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tokio-util.workspace = true
url = "2.4.1"
vc-ltl = "5.0.8"
wasmer = { version = "3.3.0", optional = true }
futures.workspace = true
console-subscriber = "0.1.10"


[features]
default = ["typescript", "react"]
typescript = ["swc_core/ecma_transforms_typescript", "swc_core/ecma_parser_typescript"]
react = ["swc_core/ecma_transforms_react"]
transpile = ["swc_core"]
wasm = []
wasmer = ["wasm", "dep:wasmer"]

[profile.release]
incremental = true
lto = "thin"
strip = "debuginfo"

[profile.min-size-release]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "s"

[profile.release-strip]
inherits = "release"
strip = "symbols"

[profile.min-size-release-strip]
inherits = "min-size-release"
strip = "symbols"

[build-dependencies]
cargo-emit = "0.2.1"
