[package]
name = "den-transpiler-oxc"
description = "Oxc-backed TypeScript/JSX transpiler for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["display", "debug", "error"] }

oxc_allocator.workspace = true
oxc_codegen.workspace = true
oxc_diagnostics.workspace = true
oxc_parser.workspace = true
oxc_semantic = { workspace = true, optional = true }
oxc_sourcemap.workspace = true
oxc_span.workspace = true
oxc_transformer = { workspace = true, optional = true }

[features]
default = ["transpile"]

typescript = ["transpile", "dep:oxc_transformer", "dep:oxc_semantic"]
react = ["transpile", "dep:oxc_transformer", "dep:oxc_semantic"]
transpile = []

[lints]
workspace = true
