[package]
name = "den-stdlib-wasm"
description = "WebAssembly JS API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
derive_more.workspace = true
either.workspace = true
indexmap.workspace = true
rquickjs = { workspace = true, features = ["macro", "futures", "array-buffer"] }
wat = "1.257.1"
wasmi = { version = "1.1.0", optional = true, features = ["simd"] }
wasmtime = { version = "48.0.0", optional = true }
wasmtime-wasi = { version = "48.0.0", optional = true }

[dev-dependencies]
rquickjs = { workspace = true, features = ["macro", "futures", "array-buffer"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = ["wasmtime"]
wasmtime = ["dep:wasmtime", "dep:wasmtime-wasi"]
wasmi = ["dep:wasmi"]

[lints]
workspace = true
