[package]
name = "den-stdlib-text"
version.workspace = true
edition.workspace = true

[dependencies]
derivative.workspace = true
derive_more.workspace = true
either.workspace = true
encoding_rs = "0.8.33"
rquickjs = { workspace = true, features = ["macro", "futures"] }
