[package]
name = "den-stdlib-text"
description = "Text API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
test = false

[dependencies]
either.workspace = true
encoding_rs.workspace = true
rquickjs = { workspace = true, features = ["macro"] }

[dev-dependencies]
color-eyre.workspace = true
den-core = { workspace = true, features = ["stdlib"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
