[package]
name = "den-stdlib-core"
version.workspace = true
edition.workspace = true

[dependencies]
delegate-attr = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
once_cell = "1.18.0"
tokio = { workspace = true, features = ["parking_lot"] }
tokio-util = { workspace = true }
rquickjs = { workspace = true, features = ["macro", "futures"] }
