import { assert, assertEquals, assertThrows } from "den:assert";
assertEquals(Blob.length, 0);
assertEquals(Blob.prototype.constructor, Blob);
assertThrows(() => Blob(), TypeError);
const blob = new Blob(["hello ", "world"], { type: "text/plain" });
assertEquals(blob.size, 11);
assertEquals(blob.type, "text/plain");
assertEquals(await blob.text(), "hello world");
assertEquals(await blob.slice(6).text(), "world");
assertEquals((await blob.arrayBuffer()).byteLength, 11);
assert(blob instanceof Blob);
