[package]
name = "den-stdlib-networking"
description = "Networking & Socket API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
derive_more.workspace = true
either.workspace = true
futures.workspace = true
rquickjs = { workspace = true, features = ["macro", "futures"] }
rustls.workspace = true
rustls-pemfile.workspace = true
rustls-platform-verifier.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "sync", "rt", "macros"] }
tokio-rustls.workspace = true
tokio-tungstenite = { workspace = true, features = ["handshake"] }
url.workspace = true

[dev-dependencies]
color-eyre.workspace = true
den-core = { workspace = true, features = ["stdlib"] }
rcgen.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time"] }

[lints]
workspace = true
