//! `docs/research/19-den-ffi.md` §6, phases 1 to 3: the scalar vocabulary and
//! borrowed buffers against a real `.so`, built here with the platform's C
//! compiler so that the ABI under test is the one this machine actually uses.

use std::{
    env,
    ffi::c_void,
    fs, iter,
    path::{Path, PathBuf},
    process::Command,
    sync::OnceLock,
};

use color_eyre::eyre;
use den_core::{FfiGrant, engine::Engine};
use libffi::middle::{Cif, CodePtr, Ret, Type};
use tempfile::TempDir;

/// The compiled probe and the fixtures that call it, in one directory that
/// lives as long as the test process.
struct Probe {
    directory: TempDir,
}

impl Probe {
    /// Built once: `cc` is slow enough, and every case wants the same library.
    /// `None` means there is no C compiler, which is a skip and not a failure —
    /// den itself does not need one.
    fn get() -> Option<&'static Self> {
        static PROBE: OnceLock<Option<Probe>> = OnceLock::new();
        PROBE
            .get_or_init(|| {
                match Self::build() {
                    Ok(probe) => probe,
                    Err(error) => panic!("could not build the FFI probe: {error}"),
                }
            })
            .as_ref()
    }

    fn build() -> eyre::Result<Option<Self>> {
        let fixtures = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests");
        let directory = TempDir::new()?;
        let library = directory.path().join("libprobe.so");
        let compiler = env::var("CC").unwrap_or_else(|_| "cc".into());
        let built = Command::new(&compiler)
            .args(["-shared", "-fPIC", "-o"])
            .arg(&library)
            .arg(fixtures.join("c/probe.c"))
            .output();
        match built {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                eprintln!(
                    "skipping den:ffi tests: no C compiler — `{compiler}` was not found (set CC)"
                );
                return Ok(None);
            }
            Err(error) => return Err(eyre::eyre!("could not run `{compiler}`: {error}")),
            Ok(output) if !output.status.success() => {
                return Err(eyre::eyre!(
                    "`{compiler}` failed to build the probe: {}",
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
            Ok(_) => {}
        }

        // The fixtures are copied next to the library so that they can name it
        // through a generated module rather than an environment variable, which
        // two tests running at once would race over.
        fs::write(
            directory.path().join("probe.js"),
            format!("export const library = {:?};\n", library.to_string_lossy()),
        )?;
        for fixture in fs::read_dir(fixtures.join("js"))? {
            let fixture = fixture?.path();
            let Some(name) = fixture.file_name() else {
                continue;
            };
            fs::copy(&fixture, directory.path().join(name))?;
        }
        Ok(Some(Self { directory }))
    }

    fn case(&self, name: &str) -> PathBuf { self.directory.path().join(name) }

    fn library(&self) -> PathBuf { self.directory.path().join("libprobe.so") }

    fn root(&self) -> &Path { self.directory.path() }
}

/// Run `name` in a realm holding `grant`, if any.
///
/// A failing fixture is reported with its JS message: `EngineError` carries
/// only "Exception generated by QuickJS", and the exception itself stays in
/// the context.
async fn run(name: &str, grant: Option<FfiGrant>) -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    let engine = Engine::new().await;
    if let Some(grant) = grant {
        engine.set_ffi_grant(grant).await?;
    }
    let outcome = engine.run_file(probe.case(name)).await;
    if outcome.is_err() {
        engine
            .context
            .with(|ctx| {
                let caught = ctx.catch();
                let message: Option<String> = caught
                    .as_object()
                    .and_then(|object| object.get("message").ok());
                eprintln!(
                    "{name}: {}",
                    message.unwrap_or_else(|| format!("{caught:?}"))
                );
            })
            .await;
    }
    Ok(outcome?)
}

/// The grant every granted case gets: the fixture directory and nothing else.
fn scoped(probe: &Probe) -> FfiGrant { FfiGrant::under([probe.root().to_path_buf()]) }

#[tokio::test(flavor = "multi_thread")]
async fn bound_symbols_call_into_c_and_refuse_after_dispose() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("calls.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn a_realm_without_a_grant_binds_nothing() -> eyre::Result<()> {
    run("denied.js", None).await
}

#[tokio::test(flavor = "multi_thread")]
async fn open_names_what_it_refuses() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("errors.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn every_scalar_width_round_trips() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("scalars.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn pointers_are_opaque_and_carry_their_library() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("pointers.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn a_buffer_is_borrowed_at_its_byte_offset_or_refused() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("buffers.js", Some(scoped(probe))).await
}

/// §0 fact 3, asserted rather than trusted: `call_return_into` writes exactly
/// `type.size()` bytes and endian-corrects a sub-register return itself. That
/// is the whole reason den's return cell is a local of the declared type
/// rather than a register-sized one — and a cell that widened would clobber
/// the byte next to it, which is what `canary` is here to notice.
///
/// This talks to libffi directly because the property is about the byte after
/// the cell, and no JS-visible value can see it.
#[test]
fn a_sub_register_return_does_not_widen_past_its_cell() {
    #[repr(C)]
    struct Guard {
        cell:   i8,
        canary: [u8; 8],
    }

    let Some(probe) = Probe::get() else {
        return;
    };
    let library = dlopen2::raw::Library::open(probe.library()).expect("the probe is loadable");
    // SAFETY: `symbol` only transmutes the `dlsym` result into a pointer-sized
    // `T` and reads nothing through it; the CIF below describes the real
    // signature of `int8_t minus_one_i8(void)`.
    let address: *const c_void =
        unsafe { library.symbol("minus_one_i8") }.expect("the probe exports it");

    let cif = Cif::new(iter::empty::<Type>(), Type::i8());
    let mut guard = Guard {
        cell:   0x7f,
        canary: [0xAA; 8],
    };
    // SAFETY: the CIF matches the C declaration, the argument list is empty as
    // it declares, and the return cell is exactly one byte, the size the CIF's
    // result type reports.
    unsafe {
        cif.call_return_into(CodePtr::from_ptr(address), &[], Ret::new(&mut guard.cell));
    }

    assert_eq!(guard.cell, -1, "an i8 return is sign-correct");
    assert_eq!(
        guard.canary, [0xAA; 8],
        "libffi wrote past a return cell sized to the declared type"
    );
}
