//! `docs/research/19-den-ffi.md` §6, phases 1 to 6: the scalar vocabulary,
//! borrowed buffers, callbacks on den's thread and on C's, and `nonblocking`
//! symbols, structs by value — all against a real `.so`, built here with the C
//! compiler of this machine, so the ABI under test is the one it really uses.

use std::{
    env,
    ffi::c_void,
    fs, iter,
    path::{Path, PathBuf},
    process::Command,
    sync::OnceLock,
    time::Duration,
};

use color_eyre::eyre;
use den_core::{FfiGrant, engine::Engine};
use libffi::middle::{Cif, CodePtr, Ret, Type};
use tempfile::TempDir;

/// The compiled probe and the fixtures that call it, in one directory that
/// lives as long as the test process.
struct Probe {
    directory: TempDir,
}

impl Probe {
    /// Built once: `cc` is slow enough, and every case wants the same library.
    /// `None` means there is no C compiler, which is a skip and not a failure —
    /// den itself does not need one.
    fn get() -> Option<&'static Self> {
        static PROBE: OnceLock<Option<Probe>> = OnceLock::new();
        PROBE
            .get_or_init(|| {
                match Self::build() {
                    Ok(probe) => probe,
                    Err(error) => panic!("could not build the FFI probe: {error}"),
                }
            })
            .as_ref()
    }

    fn build() -> eyre::Result<Option<Self>> {
        let fixtures = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests");
        let directory = TempDir::new()?;
        let library = directory.path().join("libprobe.so");
        let compiler = env::var("CC").unwrap_or_else(|_| "cc".into());
        let built = Command::new(&compiler)
            .args(["-shared", "-fPIC", "-pthread", "-o"])
            .arg(&library)
            .arg(fixtures.join("c/probe.c"))
            .output();
        match built {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                eprintln!(
                    "skipping den:ffi tests: no C compiler — `{compiler}` was not found (set CC)"
                );
                return Ok(None);
            }
            Err(error) => return Err(eyre::eyre!("could not run `{compiler}`: {error}")),
            Ok(output) if !output.status.success() => {
                return Err(eyre::eyre!(
                    "`{compiler}` failed to build the probe: {}",
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
            Ok(_) => {}
        }

        // The fixtures are copied next to the library so that they can name it
        // through a generated module rather than an environment variable, which
        // two tests running at once would race over.
        fs::write(
            directory.path().join("probe.js"),
            format!("export const library = {:?};\n", library.to_string_lossy()),
        )?;
        for fixture in fs::read_dir(fixtures.join("js"))? {
            let fixture = fixture?.path();
            let Some(name) = fixture.file_name() else {
                continue;
            };
            fs::copy(&fixture, directory.path().join(name))?;
        }
        Ok(Some(Self { directory }))
    }

    fn case(&self, name: &str) -> PathBuf { self.directory.path().join(name) }

    fn library(&self) -> PathBuf { self.directory.path().join("libprobe.so") }

    fn root(&self) -> &Path { self.directory.path() }
}

/// Run `name` in a realm holding `grant`, if any.
///
/// A failing fixture is reported with its JS message: `EngineError` carries
/// only "Exception generated by QuickJS", and the exception itself stays in
/// the context.
async fn run(name: &str, grant: Option<FfiGrant>) -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    realm(probe, name, grant).await.map(drop)
}

/// As [`run`], but hands the engine back, so that a test can ask what is still
/// keeping the realm alive after the entry module has returned.
async fn realm(probe: &Probe, name: &str, grant: Option<FfiGrant>) -> eyre::Result<Engine> {
    let engine = Engine::new().await;
    if let Some(grant) = grant {
        engine.set_ffi_grant(grant).await?;
    }
    let outcome = engine.run_file(probe.case(name)).await;
    if outcome.is_err() {
        engine
            .context
            .with(|ctx| {
                let caught = ctx.catch();
                let message: Option<String> = caught
                    .as_object()
                    .and_then(|object| object.get("message").ok());
                eprintln!(
                    "{name}: {}",
                    message.unwrap_or_else(|| format!("{caught:?}"))
                );
            })
            .await;
    }
    outcome?;
    Ok(engine)
}

/// The grant every granted case gets: the fixture directory and nothing else.
fn scoped(probe: &Probe) -> FfiGrant { FfiGrant::under([probe.root().to_path_buf()]) }

/// §5.3: the roots are the whole capability, and `Path::starts_with` on an
/// empty one is true of every path — so `--allow-ffi=` with an unset variable
/// behind it, or one stray comma, must not read as "scoped" and mean "all".
#[test]
fn an_empty_root_grants_nothing() {
    let scoped = FfiGrant::under([PathBuf::new(), PathBuf::from("/opt/den")]);
    assert!(
        !scoped.allows(Path::new("/etc/shadow")),
        "an empty root widened a scoped grant to the whole filesystem"
    );
    assert!(
        scoped.allows(Path::new("/opt/den/lib.so")),
        "the real root still counts"
    );
}

#[tokio::test(flavor = "multi_thread")]
async fn bound_symbols_call_into_c_and_refuse_after_dispose() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("calls.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn a_realm_without_a_grant_binds_nothing() -> eyre::Result<()> {
    run("denied.js", None).await
}

#[tokio::test(flavor = "multi_thread")]
async fn open_names_what_it_refuses() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("errors.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn every_scalar_width_round_trips() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("scalars.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn pointers_are_opaque_and_carry_their_library() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("pointers.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn a_buffer_is_borrowed_at_its_byte_offset_or_refused() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("buffers.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn c_calls_back_into_js_from_a_thread_of_its_own() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("callbacks.js", Some(scoped(probe))).await
}

/// The other branch of the trampoline: a stored callback fired from the realm's
/// own thread, inside a synchronous call, re-entering JS under the lock that
/// call already holds.
#[tokio::test(flavor = "multi_thread")]
async fn a_stored_callback_fires_on_the_realm_thread() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("same_thread.js", Some(scoped(probe))).await
}

/// §4.7's residual deadlock, and the only thing that breaks it: the
/// foreign-thread wait is bounded, so a callback fired into a synchronous call
/// stalls for the timeout and then hands C the zero value.
///
/// The outer timeout is what makes a regression a *failure* rather than a hung
/// test process — an unbounded `blocking_recv` here is `[exit=124]`.
#[tokio::test(flavor = "multi_thread")]
async fn a_callback_fired_into_a_synchronous_call_stalls_and_recovers() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    tokio::time::timeout(
        Duration::from_secs(60),
        run("deadlock.js", Some(scoped(probe))),
    )
    .await
    .map_err(|_elapsed| {
        eyre::eyre!("the realm never recovered: the foreign-thread wait is not bounded")
    })?
}

/// ARCHITECTURE §7.5 rule 1, for callbacks: C may call an armed one at any
/// moment, so its pump keeps the process alive, and `Symbol.dispose` is what
/// takes that back. This is why den:ffi needs no `ref()`/`unref()`.
#[tokio::test(flavor = "multi_thread")]
async fn an_armed_callback_keeps_the_realm_alive_until_it_is_disposed() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    let armed = realm(probe, "armed.js", Some(scoped(probe))).await?;
    if tokio::time::timeout(Duration::from_millis(500), armed.runtime.idle())
        .await
        .is_ok()
    {
        return Err(eyre::eyre!(
            "an armed callback must keep the event loop open"
        ));
    }

    let disposed = realm(probe, "disposed.js", Some(scoped(probe))).await?;
    tokio::time::timeout(Duration::from_secs(5), disposed.runtime.idle())
        .await
        .map_err(|_elapsed| eyre::eyre!("a disposed callback must let the event loop close"))
}

/// §0 fact 11: a realm dropped with a callback still registered must shut down
/// normally. The failure mode is not an assertion in this test but QuickJS's
/// `JS_FreeRuntime: Assertion 'list_empty(&rt->gc_obj_list)' failed`, which
/// aborts the whole test process — so reaching the end of this function *is*
/// the assertion.
#[tokio::test(flavor = "multi_thread")]
async fn a_realm_can_be_dropped_with_a_live_callback() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("leak.js", Some(scoped(probe))).await
}

/// §6: both SysV struct classes, in and out. `point_scale` is eight bytes and
/// travels in a register; `triple_sum` is twenty-four, so libffi allocates the
/// hidden `sret` pointer — a marshaller that only handles the first passes the
/// former and corrupts the stack on the latter.
#[tokio::test(flavor = "multi_thread")]
async fn structs_cross_by_value_in_both_abi_classes() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("structs.js", Some(scoped(probe))).await
}

/// §0 fact 3, asserted rather than trusted: `call_return_into` writes exactly
/// `type.size()` bytes and endian-corrects a sub-register return itself. That
/// is the whole reason den's return cell is a local of the declared type
/// rather than a register-sized one — and a cell that widened would clobber
/// the byte next to it, which is what `canary` is here to notice.
///
/// This talks to libffi directly because the property is about the byte after
/// the cell, and no JS-visible value can see it.
#[test]
fn a_sub_register_return_does_not_widen_past_its_cell() {
    #[repr(C)]
    struct Guard {
        cell:   i8,
        canary: [u8; 8],
    }

    let Some(probe) = Probe::get() else {
        return;
    };
    let library = dlopen2::raw::Library::open(probe.library()).expect("the probe is loadable");
    // SAFETY: `symbol` only transmutes the `dlsym` result into a pointer-sized
    // `T` and reads nothing through it; the CIF below describes the real
    // signature of `int8_t minus_one_i8(void)`.
    let address: *const c_void =
        unsafe { library.symbol("minus_one_i8") }.expect("the probe exports it");

    let cif = Cif::new(iter::empty::<Type>(), Type::i8());
    let mut guard = Guard {
        cell:   0x7f,
        canary: [0xAA; 8],
    };
    // SAFETY: the CIF matches the C declaration, the argument list is empty as
    // it declares, and the return cell is exactly one byte, the size the CIF's
    // result type reports.
    unsafe {
        cif.call_return_into(CodePtr::from_ptr(address), &[], Ret::new(&mut guard.cell));
    }

    assert_eq!(guard.cell, -1, "an i8 return is sign-correct");
    assert_eq!(
        guard.canary, [0xAA; 8],
        "libffi wrote past a return cell sized to the declared type"
    );
}
