//! Phase 1 of `docs/research/19-den-ffi.md` §6: `int add(int, int)` from a
//! real `.so`, built here with the platform's C compiler so that the ABI under
//! test is the one this machine actually uses.

use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
    sync::OnceLock,
};

use color_eyre::eyre;
use den_core::{FfiGrant, engine::Engine};
use tempfile::TempDir;

/// The compiled probe and the fixtures that call it, in one directory that
/// lives as long as the test process.
struct Probe {
    directory: TempDir,
}

impl Probe {
    /// Built once: `cc` is slow enough, and every case wants the same library.
    /// `None` means there is no C compiler, which is a skip and not a failure —
    /// den itself does not need one.
    fn get() -> Option<&'static Self> {
        static PROBE: OnceLock<Option<Probe>> = OnceLock::new();
        PROBE
            .get_or_init(|| {
                match Self::build() {
                    Ok(probe) => probe,
                    Err(error) => panic!("could not build the FFI probe: {error}"),
                }
            })
            .as_ref()
    }

    fn build() -> eyre::Result<Option<Self>> {
        let fixtures = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests");
        let directory = TempDir::new()?;
        let library = directory.path().join("libprobe.so");
        let compiler = env::var("CC").unwrap_or_else(|_| "cc".into());
        let built = Command::new(&compiler)
            .args(["-shared", "-fPIC", "-o"])
            .arg(&library)
            .arg(fixtures.join("c/probe.c"))
            .output();
        match built {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                eprintln!(
                    "skipping den:ffi tests: no C compiler — `{compiler}` was not found (set CC)"
                );
                return Ok(None);
            }
            Err(error) => return Err(eyre::eyre!("could not run `{compiler}`: {error}")),
            Ok(output) if !output.status.success() => {
                return Err(eyre::eyre!(
                    "`{compiler}` failed to build the probe: {}",
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
            Ok(_) => {}
        }

        // The fixtures are copied next to the library so that they can name it
        // through a generated module rather than an environment variable, which
        // two tests running at once would race over.
        fs::write(
            directory.path().join("probe.js"),
            format!("export const library = {:?};\n", library.to_string_lossy()),
        )?;
        for fixture in fs::read_dir(fixtures.join("js"))? {
            let fixture = fixture?.path();
            let Some(name) = fixture.file_name() else {
                continue;
            };
            fs::copy(&fixture, directory.path().join(name))?;
        }
        Ok(Some(Self { directory }))
    }

    fn case(&self, name: &str) -> PathBuf { self.directory.path().join(name) }

    fn root(&self) -> &Path { self.directory.path() }
}

/// Run `name` in a realm holding `grant`, if any.
///
/// A failing fixture is reported with its JS message: `EngineError` carries
/// only "Exception generated by QuickJS", and the exception itself stays in
/// the context.
async fn run(name: &str, grant: Option<FfiGrant>) -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    let engine = Engine::new().await;
    if let Some(grant) = grant {
        engine.set_ffi_grant(grant).await?;
    }
    let outcome = engine.run_file(probe.case(name)).await;
    if outcome.is_err() {
        engine
            .context
            .with(|ctx| {
                let caught = ctx.catch();
                let message: Option<String> = caught
                    .as_object()
                    .and_then(|object| object.get("message").ok());
                eprintln!(
                    "{name}: {}",
                    message.unwrap_or_else(|| format!("{caught:?}"))
                );
            })
            .await;
    }
    Ok(outcome?)
}

/// The grant every granted case gets: the fixture directory and nothing else.
fn scoped(probe: &Probe) -> FfiGrant { FfiGrant::under([probe.root().to_path_buf()]) }

#[tokio::test(flavor = "multi_thread")]
async fn bound_symbols_call_into_c_and_refuse_after_dispose() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("calls.js", Some(scoped(probe))).await
}

#[tokio::test(flavor = "multi_thread")]
async fn a_realm_without_a_grant_binds_nothing() -> eyre::Result<()> {
    run("denied.js", None).await
}

#[tokio::test(flavor = "multi_thread")]
async fn open_names_what_it_refuses() -> eyre::Result<()> {
    let Some(probe) = Probe::get() else {
        return Ok(());
    };
    run("errors.js", Some(scoped(probe))).await
}
