[package]
name = "den-stdlib-assert"
description = "JSR @std/assert for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
den-util.workspace = true
rquickjs = { workspace = true, features = ["macro", "futures"] }

[dev-dependencies]
den-core = { workspace = true, features = ["stdlib"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
