[package]
name = "den-stdlib-http"
description = "HTTP server API for den"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
bytes.workspace = true
den-stdlib-core.workspace = true
den-stdlib-whatwg.workspace = true
den-util.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["http1", "http2", "server"] }
hyper-util = { workspace = true, features = ["server-auto", "tokio"] }
rquickjs = { workspace = true, features = ["macro", "futures"] }
tokio = { workspace = true, features = ["net", "sync", "time"] }

[dev-dependencies]
color-eyre.workspace = true
den-core = { workspace = true, default-features = false, features = ["stdlib-http", "stdlib-networking"] }
reqwest.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "time"] }

[features]
default = ["ring"]
ring = ["den-stdlib-whatwg/ring"]

[lints]
workspace = true
