name: lint



permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.rs"
      - .github/workflows/lint.yml

jobs:
  clippy:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: olix0r/cargo-action-fmt/setup@v2
      - uses: actions/checkout@v2
      - run: rustup install nightly --profile complete
      - run: cargo +nightly clippy --no-deps --message-format=json | cargo-action-fmt

  fmt:
    runs-on: [self-hosted, ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: olix0r/cargo-action-fmt/setup@v2
      - uses: actions/checkout@v2
      - run: rustup install nightly --profile complete
      - run: cargo +nightly fmt --check

  docs:
    runs-on: [self-hosted, ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: olix0r/cargo-action-fmt/setup@v2
      - uses: actions/checkout@v2
      - run: rustup install nightly --profile complete
      - run: cargo +nightly doc --no-deps --message-format=json | cargo-action-fmt
